### ISSUE TITLE
Building Error (weird)

### ISSUE THREAD

**Issue by nathanaelnoir** [janosh/blog#67]
After successfully developing the blog, if tried to rebuild it on Netlify - without success. 

I retried to develop local but now the following strange error occurs:

```
Error: /Users/noir/blog/gatsby-node.js:52
      const nextSlug = arr[index - 1]?.frontmatter.slug || ``
                                      ^
  SyntaxError: Unexpected token '.'
```

It's also kinda strange that the develop is working without problem, but the build fails.

Has anyone had a similar issue?

**Comment by nathanaelnoir** [comment]
I could fix the develop error by downgrade to another node version. But on build (Netlify) I get still an error:

```
error "gatsby-plugin-sitemap" threw an error while running the onPostBuild lifecycle:
Cannot use 'in' operator to search for 'nodes' in undefined
   40 |           case 9:
    41 |             queryRecords = _context.sent;
> 42 |             filteredRecords = (0, _internals.filterQuery)(queryRecords, excludeOptions, basePath, resolveSiteUrl);
         |                                                          ^
    43 |             urls = serialize(filteredRecords);
    44 | 
    45 |             if (!(!rest.sitemapSize || urls.length <= rest.sitemapSize)) {
```

**Comment by janosh** [comment]
> After successfully developing the blog, if tried to rebuild it on Netlify - without success.

That is not entirely unexpected. I sometimes get time-outs on netlify depending on how much has changed and how much of the build could be cached. So I usually build locally and then push it to production with the Netlify CLI (`gatsby build && netlify deploy --prod`).

> I retried to develop local but now the following strange error occurs:
> const nextSlug = arr[index - 1]?.frontmatter.slug || ``
> SyntaxError: Unexpected token '.'

That looks like you're running a version of `node` that doesn't support optional chaining yet. I would try to upgrade to [`node` v14.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2020-04-21-version-1400-current-bethgriggs) or above.

> error "gatsby-plugin-sitemap" threw an error while running the onPostBuild lifecycle:

Ah yes, I had that error too which is why I got rid of `gatsby-plugin-sitemap` again for now (but didn't push that yet) until [gatsby#22757](https://github.com/gatsbyjs/gatsby/issues/22757) fixes it.

**Comment by nathanaelnoir** [comment]
> Ah yes, I had that error too which is why I got rid of gatsby-plugin-sitemap again for now (but didn't push that yet) until gatsby#22757 fixes it.

That did the job! Thank you very much for your support!
