### ISSUE TITLE
Author extension for blog

### ISSUE THREAD

**Issue by nathanaelnoir** [janosh/blog#70]
Hi Janosh, 

I was wondering if it is possible to easily implement in your personal blog a feature that you use in your other websites. Strictly speaking, the possibility to add an author to blog entries with a small picture of the author. As far as I've seen, 
`./src/components/PostMeta` and `./src/templates/post.js`
 needs to be adjusted. 
Is there more to consider here or do you even need a plugin?

Best, Nathanael

**Comment by janosh** [comment]
> As far as I've seen, `./src/components/PostMeta` and `./src/templates/post.js` needs to be adjusted.

That's correct.

> Is there more to consider here or do you even need a plugin?

Depends on where the author images are coming from. If you read them from the file system, this site already uses [`gatsby-source-filesystem`](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem) so no extra plugins required.

**Comment by nathanaelnoir** [comment]
> Depends on where the author images are coming from. If you read them from the file system, this site already uses gatsby-source-filesystem so no extra plugins required.

How exactly did you do that/save the pictures? I could not find the location, so I thought these pictures might be found in the individual blog post folders and will be called in the .md files such as title, slug, date, cover, tag, etc.

If so, what is the term to use here? Since most blogs hide their content files it is a little bit hard to find the solution. Thanks in advance.

**Comment by janosh** [comment]
The other sites you're referring to all use Contentful as their CMS. That's where the author photos are sourced from. For a personal blog running off the filesystem, I guess it makes sense to have a folder like `/content/authors` with a `authors.yml` file in it that lists authors names along with any metadata you care for as well as the file path to their photos stored in the same folder:
```yml
# authors.yml
- name: Nathanael Noir
  id: nnoir
  bio: Hello World
  ...
  img: nathanaelnoir.jpg

- name: Another Author
  ...
```

You can then grab all of that data from Gatsby's GraphQL layer (since `gatsby-transformer-yaml` is also already installed) and use the `id` to link authors to posts by including the author ID in the posts frontmatter.

**Comment by janosh** [comment]
Please reopen if questions remain.
